#nullable enable
using System.CodeDom.Compiler;
using AST.Hlsl.Syntax;
using AST.Hlsl.Syntax.Expressions;
using AST.Hlsl.Syntax.Expressions.Operators;
using AST.Hlsl.Syntax.Preprocessor;
using AST.Hlsl.Syntax.Statements;
using AST.Syntax;

namespace AST.Hlsl.Syntax                                                                        { public partial record ArgumentList<T>                                                     { public ArgumentList() { openParenToken = new(); arguments = SeparatedList<Hlsl, T>.Empty;closeParenToken = new(); } } }
namespace AST.Hlsl.Syntax                                                                        { public partial record BracedList<T>                                                       { public BracedList() { openBraceToken = new(); arguments = SeparatedList<Hlsl, T>.Empty; closeBraceToken = new(); } } }
namespace AST.Hlsl.Syntax                                                                        { public partial record Semantic                                                            { public Semantic() { colonToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record Initializer                                                         { public Initializer() { equalsToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements               {  public partial record Switch               { public partial record DefaultCase                                                         { public DefaultCase() { defaultKeyword = new(); colonToken = new(); body = new(); } } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record Break                                                               { public Break() { breakKeyword = new(); semiToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record ExpressionStatement                                                 { public ExpressionStatement() { semiToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record Discard                                                             { public Discard() { discardKeyword = new();  semiToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record Switch                                                              { public Switch() { switchKeyword = new(); openParen = new(); closeParen = new(); cases = new(); } } }
namespace AST.Hlsl.Syntax.Statements.Declarations                                                { public partial record StructDeclaration                                                   { public StructDeclaration() { semicolon = new(); } } }
namespace AST.Hlsl.Syntax.Statements.Declarations                                                { public partial record VariableDeclaration                                                 { public VariableDeclaration() { semiToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements               {  public partial record If                   { public partial record ElseClause                                                          { public ElseClause() { elseKeyword = new(); } } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record If                                                                  { public If() { ifKeyword = new(); openParen = new(); closeParen = new(); } } }
namespace AST.Hlsl.Syntax.Statements               {  public partial record Switch               { public partial record Case                                                                { public Case() { caseKeyword = new(); colonToken = new(); body = new(); } } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record Continue                                                            { public Continue() { continueKeyword = new(); semiToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record Block                                                               { public Block() { openBraceToken = new(); statements = new(); closeBraceToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record While                                                               { public While() { whileKeyword = new(); openParen = new(); closeParen = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record Return                                                              { public Return() { returnKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record For                                                                 { public For() { forKeyword = new(); openParen = new(); firstSemiToken = new(); secondSemiToken = new(); closeParen = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record DoWhile                                                             { public DoWhile() { doKeyword = new(); openBraceToken = new(); closeBraceToken = new(); whileKeyword = new(); openParenToken = new(); closeParenToken = new(); semicolonToken = new(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { public partial record Typedef                                                             { public Typedef() { typedefKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { public partial record Ternary                                                             { public Ternary() { questionToken = new(); colonToken = new(); } } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { public partial record Comma                                                               { public Comma() { comma = new(); } } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { public partial record Indexer                                                             { public Indexer() { openBracketToken = new(); closeBracketToken = new(); } } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { public partial record Cast                                                                { public Cast() { openParenToken = new(); arrayRankSpecifiers = new(); closeParenToken = new(); } } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { public partial record AssignmentExpression                                                { public AssignmentExpression() { assignmentToken = new EqualsToken(); } } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { public partial record Member                                                              { public Member() { dotToken = new(); } } }
namespace AST.Hlsl.Syntax.Expressions                                                            { public partial record StructInitializer                                                   { public StructInitializer() { components = new(); } } }
namespace AST.Hlsl.Syntax.Expressions                                                            { public partial record Parenthesized                                                       { public Parenthesized() { openParen = new(); closeParen = new(); } } }
namespace AST.Hlsl.Syntax                                                                        { public partial record ArrayRank                                                           { public ArrayRank() { closeBracketToken = new(); } } }
namespace AST.Hlsl.Syntax                          {  public partial record Type                 { public partial record Struct                                                              { public Struct() { structKeyword = new(); openBrace = new(); closeBrace = new(); } } } }
namespace AST.Hlsl.Syntax                          {  public partial record Type                 { public partial record Struct                   { public partial record Member             { public Member() { semicolon = new(); } } } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Line                                                                { public Line() { lineKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Ifndef                                                              { public Ifndef() { ifndefKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Undef                                                               { public Undef() { undefKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Define                                                              { public Define() { defineKeyword = new(); argList = new() { arguments = SeparatedList<Hlsl, Identifier>.Empty }; } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record If                                                                  { public If() { ifKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Else                                                                { public Else() { elseKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Elif                                                                { public Elif() { elifKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Error                                                               { public Error() { errorKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Ifdef                                                               { public Ifdef() { ifdefKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Endif                                                               { public Endif() { endifKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record Pragma                                                              { public Pragma() { pragmaKeyword = new(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { public partial record PreprocessorSyntax                                                  { public PreprocessorSyntax() { hashToken = new(); } } }