#nullable enable
using System.CodeDom.Compiler;
using AST.Hlsl.Syntax;
using AST.Hlsl.Syntax.Expressions;
using AST.Hlsl.Syntax.Expressions.Operators;
using AST.Hlsl.Syntax.Preprocessor;
using AST.Hlsl.Syntax.Statements;
using AST.Syntax;

namespace AST.Hlsl.Syntax                                                                        { /*./Identifier.cs:                                 */ public partial record Identifier                                                          { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax                                                                        { /*./Lists.cs:                                      */ public partial record ArgumentList<T>                                                     { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax                                                                        { /*./Lists.cs:                                      */ public partial record BracedList<T>                                                       { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax                                                                        { /*./Semantic.cs:                                   */ public partial record Semantic                                                            { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/Initializer.cs:                     */ public partial record Initializer                                                         { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements               {  public partial record Switch               { /*./Statements/Switch.DefaultCase.cs:              */ public partial record DefaultCase                                                         { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/Break.cs:                           */ public partial record Break                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/ExpressionStatement.cs:             */ public partial record ExpressionStatement                                                 { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/Discard.cs:                         */ public partial record Discard                                                             { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements               {  public partial record For                  { /*./Statements/For.VariableInitializer.cs:         */ public partial record VariableInitializer                                                 { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/Switch.cs:                          */ public partial record Switch                                                              { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements.Declarations                                                { /*./Statements/Declarations/StructDeclaration.cs:  */ public partial record StructDeclaration                                                   { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements.Declarations                                                { /*./Statements/Declarations/VariableDeclaration.cs:*/ public partial record VariableDeclaration                                                 { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements.Declarations                                                { /*./Statements/Declarations/FunctionDeclaration.cs:*/ public partial record FunctionDeclaration                                                 { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements.Declarations  {  public partial record FunctionDeclaration  { /*./Statements/Declarations/FunctionDeclaration.cs:*/ public partial record Parameter                                                           { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax.Statements               {  public partial record If                   { /*./Statements/If.ElseClause.cs:                   */ public partial record ElseClause                                                          { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/If.cs:                              */ public partial record If                                                                  { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements               {  public partial record Switch               { /*./Statements/Switch.Case.cs:                     */ public partial record Case                                                                { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/Continue.cs:                        */ public partial record Continue                                                            { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/Block.cs:                           */ public partial record Block                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/While.cs:                           */ public partial record While                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/Return.cs:                          */ public partial record Return                                                              { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/For.cs:                             */ public partial record For                                                                 { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/DoWhile.cs:                         */ public partial record DoWhile                                                             { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Statements                                                             { /*./Statements/Typedef.cs:                         */ public partial record Typedef                                                             { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions                                                            { /*./Expressions/LiteralExpression.cs:              */ public partial record LiteralExpression<T>                                                { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Ternary.cs:              */ public partial record Ternary                                                             { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Comma.cs:                */ public partial record Comma                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Indexer.cs:              */ public partial record Indexer                                                             { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Cast.cs:                 */ public partial record Cast                                                                { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Binary.cs:               */ public partial record Binary                                                              { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Call.cs:                 */ public partial record Call                                                                { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/AssignmentExpression.cs: */ public partial record AssignmentExpression                                                { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Member.cs:               */ public partial record Member                                                              { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Affix.cs:                */ public partial record Affix                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Affix.cs:                */ public partial record Affix                    { public partial record Pre                { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Affix.cs:                */ public partial record Affix                    { public partial record Post               { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax.Expressions.Operators                                                  { /*./Expressions/Operators/Unary.cs:                */ public partial record Unary                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions                                                            { /*./Expressions/StructInitializer.cs:              */ public partial record StructInitializer                                                   { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Expressions                                                            { /*./Expressions/Parenthesized.cs:                  */ public partial record Parenthesized                                                       { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax                                                                        { /*./VariableDeclarator.cs:                         */ public partial record VariableDeclarator                                                  { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax                                                                        { /*./VariableDeclarator.cs:                         */ public partial record VariableDeclarator       { public partial record VariableDefinition { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax                                                                        { /*./ArrayRank.cs:                                  */ public partial record ArrayRank                                                           { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax                          {  public partial record Type                 { /*./Type.Struct.cs:                                */ public partial record Struct                                                              { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax                          {  public partial record Type                 { /*./Type.Struct.cs:                                */ public partial record Struct                   { public partial record Member             { public override string ToString() => base.ToString(); } } } }
namespace AST.Hlsl.Syntax                          {  public partial record Type                 { /*./Type.Predefined.cs:                            */ public partial record Predefined                                                          { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax                          {  public partial record Type                 { /*./Type.UserDefined.cs:                           */ public partial record UserDefined                                                         { public override string ToString() => base.ToString(); } } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Line.cs:                          */ public partial record Line                                                                { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Ifndef.cs:                        */ public partial record Ifndef                                                              { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Include.cs:                       */ public partial record Include                                                             { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Undef.cs:                         */ public partial record Undef                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Define.cs:                        */ public partial record Define                                                              { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/If.cs:                            */ public partial record If                                                                  { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Else.cs:                          */ public partial record Else                                                                { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Elif.cs:                          */ public partial record Elif                                                                { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Error.cs:                         */ public partial record Error                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Ifdef.cs:                         */ public partial record Ifdef                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Endif.cs:                         */ public partial record Endif                                                               { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/Pragma.cs:                        */ public partial record Pragma                                                              { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Preprocessor                                                           { /*./Preprocessor/PreprocessorSyntax.cs:            */ public partial record PreprocessorSyntax                                                  { public override string ToString() => base.ToString(); } }
namespace AST.Hlsl.Syntax.Trivias                                                                { /*./Trivias/PreprocessorDirectives.cs:             */ public abstract partial record PreprocessorDirective                                      {                                                              public override string ToString() => base.ToString(); } }